<?php

include_once('sy_commerce_add_functions.inc');
include_once('sy_commerce_add_block.inc');


function sy_commerce_add_menu() {
    $items = array();

    $items['change-sity'] = array(
        'page callback' => 'sy_commerce_add_change_sity',
        'page arguments' => array(1),
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function sy_commerce_add_ctools_plugin_directory($owner, $plugin_type){
    if ($owner == 'feeds_tamper' && $plugin_type == 'plugins') {
        return 'plugins';
    }
}

function sy_commerce_add_form_commerce_cart_add_to_cart_form_alter(&$form, &$form_state, $form_id)
{
    if(isset($form_state['context']['entity_id']) && $form_state['context']['view_mode']=='node_full' && isset($form_state['default_product']->type) && $form_state['default_product']->type=='product') {
        if (!isset($form_state['list_product_in_stok'])) $form_state['list_product_in_stok'] = sy_commerce_add_get_list_product_in_stocks($form_state['context']['entity_id']);
        $city_stocks = sy_commerce_add_get_city_stocks_in($form_state['list_product_in_stok']);
        $city_stocks_all = sy_commerce_add_get_city_stocks();
        $keys_location = array_keys($city_stocks_all);
        if(count($city_stocks_all)>0) {

            $form['#prefix'] = '<div id="cart-gip-form-wrapper">';
            $form['#suffix'] = '</div>';

            if (isset($form_state['values']['city'])) {
                $def_city = $form_state['values']['city'];
            } elseif (isset($_SESSION['sy_commerce_add_city']) /* && array_key_exists($_SESSION['sy_commerce_add_city'], $city_stocks) */) {
                $def_city = $_SESSION['sy_commerce_add_city'];
            } else {
                $city_location = sy_commerce_add_get_city_stocks_location();
                if (is_string($city_location) && in_array($city_location, $city_stocks_all)) {
                    $def_city = $city_location;
                } else {
                    $def_city = $keys_location[0];
                }
            }
            /*
            $form['city'] = array(
                '#type' => 'select',
                '#title' => 'Город',
                '#default_value' => $def_city,
                '#options' => $city_stocks_all,
                '#ajax' => array(
                    'callback' => 'sy_commerce_add_city_choice_js',
                    'wrapper' => 'cart-gip-form-wrapper',
                    'method' => 'replace',
                    'effect' => 'fade',
                ),
            );
            */
            $form['table']=sy_commerce_add_get_stocks_table($form_state['context']['entity_id'],$def_city);

            if(array_key_exists($def_city, $city_stocks) ) {
                $options_product = sy_commerce_add_get_options_product($form_state['list_product_in_stok'], $def_city);
                $form['product_id']['#options'] = $options_product;
            }
            else
            {
                $form['product_id']['#disabled'] = TRUE;
                $form['product_id']['#attributes']['style'] = 'display:none;';
                $form['quantity']['#disabled'] = TRUE;
                $form['submit']['#disabled'] = TRUE;
            }
        }
        else
        {
            $form['city_information'] = array('#markup' => 'Нет городов', );
        }

    }
}

function sy_commerce_add_city_choice_js($form, &$form_state)
{
//    $_SESSION['sy_commerce_add_city'] = $form_state['values']['city'];
    $form_state['no_cache'] = TRUE;
    $form_state['rebuild'] = TRUE;
    return commerce_cart_add_to_cart_form_attributes_refresh($form, $form_state);

}



function sy_commerce_add_feeds_after_import(FeedsSource $source) {
    // watchdog('sy commerce add',$source->id . '  =  '.variable_get('sy_commerce_add_cron',0));
    // похоже сам себя не запускает :(
    if ($source->id == 'import_catalog_pharm'  || $source->id == 'import_display_product_pharm') {
        variable_set('sy_commerce_add_cron',($source->id == 'import_display_product_pharm'?2:1));
        watchdog('sy commerce add','step 2');
        $fetcher_config = $source->getConfigFor($source->importer->fetcher);
        $second_source = feeds_source('import_product_pharm');
        $second_source->setConfigFor($second_source->importer->fetcher, $fetcher_config);
        $second_source->save();
        $second_source->startImport();

    }
    elseif ($source->id == 'import_product_pharm' && variable_get('sy_commerce_add_cron',0)!=2 ) {
        watchdog('sy commerce add','step 3');
        $fetcher_config = $source->getConfigFor($source->importer->fetcher);
        $second_source = feeds_source('import_display_product_pharm');
        $second_source->setConfigFor($second_source->importer->fetcher, $fetcher_config);
        $second_source->save();
        $second_source->startImport();
    }
    elseif ($source->id == 'import_product_pharm' && variable_get('sy_commerce_add_cron',0)==2 ) {
        db_update('node')
            ->fields(array('status' => 0))
            ->condition('type', 'product_display')
            ->condition('uid', 0)
            ->execute();

        watchdog('sy commerce add','step 4');
        file_unmanaged_delete('public://feeds-tmp/import.xml');
        variable_set('sy_commerce_add_cron',0);
    }
}
function sy_commerce_add_cron()
{
    //db_query('update elysia_cron set running = 0'); разблокировка
    $output = sy_commerce_add_get_orders_xml();
    file_unmanaged_save_data($output , drupal_realpath('public://feeds-tmp/output.xml'), FILE_EXISTS_REPLACE);
    watchdog('sy commerce add', 'GO');
    $source=drupal_realpath('public://feeds-tmp/import.xml');

    if(file_exists($source)) watchdog('sy commerce add','file is & var='.variable_get('sy_commerce_add_cron',0));
    if(variable_get('sy_commerce_add_cron',0)<1) watchdog('sy commerce add','cron 0');
    if(file_exists($source) && variable_get('sy_commerce_add_cron',0)==0) {
        watchdog('sy commerce add','step 1');



        db_update('node')
            ->fields(array('uid' => 0))
            ->condition('type', 'product_display')
            ->execute();


        variable_set('sy_commerce_add_cron',1);
        $myFeed = feeds_source('import_catalog_pharm');
        $config = array('FeedsFileFetcher' => array('source' => $source));
        $myFeed->addConfig($config);
        $myFeed->import();
    }
    elseif(!file_exists($source) )
    {
//        watchdog('sy commerce add',' not file_exists');
        variable_set('sy_commerce_add_cron',0);
    }
    else
    {
        //   watchdog('sy commerce add','not');
    }
}


function sy_commerce_add_get_orders_xml()
{
    $out='<?xml version="1.0" encoding="UTF-8" ?>'." \n";
    $oids = db_query("SELECT order_id FROM {commerce_order} WHERE status=:status", array(':status'=>'pending'))->fetchCol();
    $orders=commerce_order_load_multiple($oids);
    if(count($orders)>0) {
        $out .= "<commerce_orders> \n";
        foreach ($orders as $order) {
            $out .= "<commerce_order> \n";
            $out .= "<ID-order>$order->order_id</ID-order> \n";
            $out .= "<E-mail>$order->mail</E-mail> \n";
            $out .= "<Date-created>" . date("d/m/Y - H:i", $order->created) . "</Date-created> \n";
            $out .= "<Order-total>" . ($order->commerce_order_total['und'][0]['amount'] / 100) . "</Order-total> \n";
            $out .= "<list-products>" . sy_commerce_add_get_orders_xml_lines($order->order_id,$out) . "</list-products> \n";
            $out .= "</commerce_order> \n";
        }
        $out .= "</commerce_orders> \n";

        return $out;
    }
    else
    {
        return '';
    }
}
function sy_commerce_add_get_orders_xml_lines($order_id,&$out) {
    $oids = db_query("SELECT prd.title, prc.commerce_price_amount, prd.sku, cli.quantity, adqt.quantity as add_qty 
                    FROM {commerce_line_item} AS cli
                    LEFT JOIN {commerce_product} AS prd ON prd.sku = cli.line_item_label
                    LEFT JOIN {field_data_commerce_price} AS prc ON prc.entity_id = prd.product_id 
                    LEFT JOIN {sy_commerce_add_quantity} AS adqt ON adqt.line_item_id = cli.line_item_id  
                    WHERE cli.order_id = :order_id AND cli.type = 'product'",array(':order_id'=>$order_id));
    foreach ($oids as $key=>$val)
    {
        $out.="<product> \n";
        $out.="<name>$val->title</name> \n";
        $out.="<SKU>$val->sku</SKU> \n";
        $out.="<price>".($val->commerce_price_amount/100)."</price> \n";
        $out.="<qty>$val->quantity</qty> \n";
        $out.="<qty-add>".($val->add_qty!=0?$val->add_qty:0)."</qty-add> \n";
        $out.="</product> \n";
    }
}